Game
tretikoff/rougelike pull request #1
Opened 2021-04-04 17:14 UTC by tretikoff

2021-05-02 12:24 UTC, FirstTimeInForever requested changes
Смотрел на `9fee8fc459619d09758d3aa71f39d2f83fd51dc1`.

* Нет инструкции по запуску
* Столкнулся с такими ошибками:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.lwjgl.LWJGLUtil$3 (file:/Users/hans/.gradle/caches/modules-2/files-2.1/org.lwjgl.lwjgl/lwjgl/2.9.3/3df168ac74e4a8c96562cdff24ad352e255bf89c/lwjgl-2.9.3.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.lwjgl.LWJGLUtil$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
AL lib: (WW) FreeDevice: (0x7fb13c217000) Deleting 5 Buffer(s)
Exception in thread "LWJGL Application" io.ktor.client.features.ServerResponseException: Server error(http://localhost:8084/hit: 500 Internal Server Error. Text: ""
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:48)
	at io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)
	at io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:55)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invokeSuspend(HttpCallValidator.kt:134)
	at io.ktor.client.features.HttpCallValidator$Companion$install$3.invoke(HttpCallValidator.kt)
	at io.ktor.client.features.HttpSend$Feature$install$1.invokeSuspend(HttpSend.kt:98)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:191)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:147)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:86)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.bomjRogue.game.GameClient.hit(GameClient.kt:184)
	at com.bomjRogue.game.GameClient.movePlayer(GameClient.kt:277)
	at com.bomjRogue.game.GameClient.handleInput(GameClient.kt:237)
	at com.bomjRogue.game.GameClient.render(GameClient.kt:179)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:232)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:127)

Process finished with exit code 0
```

```
Exception in thread "LWJGL Application" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 15000 ms
	at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
	at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:507)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

* Иногда на карте появлятся два игрока (я играл явно один)

Считаю что получилось годно, но есть не очень большие проблемы. Пожалуйста исправьте замечания.

За первое задание `7/10`, за второе `7/10`.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/Server.kt
> +    val gson = GsonBuilder().enableComplexMapKeySerialization().setPrettyPrinting().create()
Зачем вам `gson` когда есть `kotlinx.serialization`?

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/config/Utils.kt
> +    companion object {
```suggestion
object Utils {
```

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/config/Utils.kt
> +    companion object {
```suggestion
object SettingsManager {
```

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/Server.kt
> +    embeddedServer(Netty, host = "127.0.0.1", port = 8084) {
Обычно это выносят в аргументы программы или в конфиг файл.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/game/command/Command.kt
> +}
Вот это не очень хорошее решение. Смотрите: вы сделали специальный открытый класс `Command` для того чтобы наследовать от него команды. Но когда вы захотите создать новую команду, вам нужно будет добавлять дополнительное поле в это перечисление перед тем как отнаследоваться от `Command`. Поинт в том, что это неудобно расширять. Лучше избавиться от `CommandType` т. к. он у вас, кажется нигде не используется, да и можно использовать сами типы (`::class`) вместо него.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/game/strategy/MovementStrategy.kt
> +    }
В фабрике нужно отдавать общий тип (`MovementStrategy`) иначе её смысл теряется т. к. вы выставляете наружу имплементацию, которую вы хотели спрятать в фабрике.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/world/LevelGenerator.kt
> +            return Map(MazeGenerator(13, 7).getMaze(), 720f, 1280f)
Эти магические числа ведь как-то связаны с размером окна? Не нужно их хардкодить.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/game/GameClient.kt
> +    private lateinit var knownSounds: Map<String, Sound>
Вам нужен  какой-нибудь`AssetManager` и `MusicManager`. Потому что этот код явно стоит вынести в другое место.

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/game/strategy/MovementStrategy.kt
> +    }
Зачем вашей фабрике стейт? И почему тогда этот стейт глобальный?

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/world/interactive/GameObject.kt
> +}
Опять же, плохо расширяется. У вас всего есть 3 класса сущностей:
* декорации (стены/двери/камни)
* живые существа
* предметы

Конкретные предметы/стены/нпц вы можете реализовать отнаследовавшись от этих базовых сущностей. При этом для того чтобы их различать не понадобится иметь какой-то `ObjectType` - им будет сам тип (::class). Понятно, что тогда можно реализовывать такие иерархии: `Item <- Weapon <- Sword`, `Item <- Potion <- HealthPotion`, `Block <- Wall`, `Creature <- Enemy <- Goblin`, `Creature <- Neutral <- Merchant` - ну вы поняли.

Думаю с этой идеей вы сможете избавиться от этого перечисления :).

2021-05-02 12:24 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/game/strategy/MovementStrategy.kt
> +    }
Я бы избавился от этого метода и перечисления т. к. добавление новой стратегии требует изменения кода перечисления.

2021-05-07 05:53 UTC, tretikoff commented
По клавише F10 можно включить локальный мультиплеер. Добавим явно в инструкции
> * Иногда на карте появлятся два игрока (я играл явно один)

2021-05-07 09:38 UTC, tretikoff commented on src/main/kotlin/com/bomjRogue/Server.kt
> +    val gson = GsonBuilder().enableComplexMapKeySerialization().setPrettyPrinting().create()
В `kotlinx.serialization` плохо работает сериализация `Map`-ов

2021-05-25 22:28 UTC, FirstTimeInForever commented on src/main/kotlin/com/bomjRogue/Server.kt
> +    val gson = GsonBuilder().enableComplexMapKeySerialization().setPrettyPrinting().create()
Она там работает хорошо, просто если вы сериализуете контейнеры и хотите явно восстанавливать его тип, то вам нужно задавать свои сериализаторы. Например, если вы сериализуете `ConcurrentHashMap` дефолтным сериализатором, то после десериализации вы получите обычный `HashMap`. Вообще, хорошая библиотека, но ладно :)

2021-05-25 22:45 UTC, FirstTimeInForever requested changes
Насколько я понимаю, можно проверять. Мультиплеер работает окей, но если убить второго игрока вываливается эксепшн:
```
Exception in thread "LWJGL Application" kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 15000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:507)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
        at java.base/java.lang.Thread.run(Thread.java:832)
```

Всё остальное клёво. В целом хорошо сделано 👍 . `10/10`, `10/10`, `8/10`.

2021-06-01 04:49 UTC, closed without merging